#!/bin/bash
# чтобы запустить скрипт : "https://raw.githubusercontent.com/admin-ig/centos/master/basic_setup"
## Базовая настройка сервера

sudo yum update -y 
# sudo yum install -y open-vm-tools
sudo yum install -y net-tools bind-utils nano bash-completion wget mc

# установить ntp клиент
sudo yum install -y ntpdate 
sudo ntpdate pool.ntp.org

sudo yum install -y openssh-server
sudo systemctl enable sshd

# настройка ssh
sudo sed -i '/^PermitRootLogin/d' /etc/ssh/sshd_config 		# Удалить сторку начинающуюся с "PermitRootLogin"
sudo sed -i '/^#PermitRootLogin/d' /etc/ssh/sshd_config 	# Удалить сторку начинающуюся с "#PermitRootLogin"
sudo sed -i '/^AllowUsers/d' /etc/ssh/sshd_config 		    # Удалить сторку начинающуюся с "AllowUsers"
sudo sed -i '1 i PermitRootLogin no' /etc/ssh/sshd_config # Дописать первой строкой "PermitRootLogin no"
sudo sed -i "1 i AllowUsers $USER" /etc/ssh/sshd_config 	# Дописать первой строкой "AllowUsers $USER" ($USER - перемення окружения с именем текущего пользователя)
sudo systemctl restart sshd

# fail2ban
sudo yum install -y epel-release
sudo yum install -y fail2ban
sudo su -c "cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
# Ban hosts for one hour:
bantime = 3600
# Override /etc/fail2ban/jail.d/00-firewalld.conf:
banaction = iptables-multiport
[sshd]
enabled = true
EOF"
sudo systemctl enable fail2ban
sudo systemctl restart fail2ban


# отключаем firewall, включаем iptables
sudo systemctl disable firewalld.service
sudo systemctl stop firewalld.service
sudo yum  install -y iptables-services iptables-utils
sudo systemctl enable iptables.service

# отключение IPv6
sudo sh -c "echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf" 
sudo sh -c "echo 'net.ipv6.conf.default.disable_ipv6 = 1' >> /etc/sysctl.conf"
sudo sysctl -p

# правила iptables
sudo su -c "cat > /etc/sysconfig/iptables <<EOF
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
# Allows all loopback (lo0) traffic and drop all traffic to 127/8 that doesn't use lo0
-A INPUT -i lo -j ACCEPT
-A INPUT ! -i lo -d 127.0.0.0/8 -j REJECT
# Allow SSH
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
# Accepts all established inbound connections
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
# Reject all other
-A INPUT -j REJECT --reject-with icmp-port-unreachable
COMMIT
EOF"
sudo systemctl restart iptables.service

# SELINUX
sudo sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/sysconfig/selinux
